### PR TITLE
Change ECR Workflows

### PR DESCRIPTION
**Pull request by codyfletcher**
Note: I operate under the definition of "refactor" to mean "does not change the behavior of the system".

1. This PR is all refactoring
2. The goal is to bring these files inline with each other, and easily spot differences between the 2 files
3. Removed unused `environment: terraform-aws-ecs` in ecr_frontend.yml
4. Replaced `ref: ${{ github.event.inputs.git_tag }}` with `ref: ${{ github.ref_name }}` in ecr_frontend.yml
5. Change tag prefix from `be`/`fe` to `backend`/`frontend` (for clarity/ease of understanding)

## To Discuss:

1. For manual testing purposes, I added modified both of these with an empty `workflow_dispatch:`. I'd like to add that here but wanted to make sure they worked as intended.

### CODE REVIEW

**Review by briancaffey — APPROVED** [review]
Thanks @codyfletcher, these changes look great!

A good next step for the jobs that build the frontend and backend images would be to use the official docker `build-and-push` action: https://github.com/marketplace/actions/build-and-push-docker-images.

This would help to keep the action a little bit cleaner. Part of me does like being able to see the underlying docker CLI command in the action, but using this action seems like a more standard way of doing this.

**Comment by briancaffey** [comment]
Thanks @codyfletcher, I added some comments about your questions above:

Correct, we don't need `environment` on these jobs, I'm not sure why I added that originally.

I'm fine with changing fe/be to frontend/backend. This is only needed since these projects live in the same repo. If the frontend was in its own repo we wouldn't need to prefix the tags. 

The checkout actions should actually only have `- uses: actions/checkout@v3`. Fetch depth of 0 fetches all tags and branches, which we don't need. When the build is triggered by fe/v1.2.3, the checkout action automatically checks out that version of the code (fe/v1.2.3). I learned this recently but had not changed it in this project.

`${{ github.ref_name }}` is probably the better one to use here

**Comment by codyfletcher** [comment]
I pushed a few more commits and update the top PR description to include the changes. It looks like the remaining things on this are:

1. Replace `actions/checkout@v2` with `actions/checkout@v3` – Do we want to make this change in all workflows? If so, I think it'd make a nice/simple/clean separate PR. I'm happy to do that if you like. Maybe we could remove all the `fetch-depth: 0` in that PR. Thoughts?
2. `workflow_dispatch` – I've been using this to kick off workflows, which is really handy when you're working on things in a branch and pushing commits every few minutes. Thoughts on including this?

**Comment by briancaffey** [comment]
@codyfletcher sure, we can do the fetch depth changes in a separate PR. 

I think it is fine to include `workflow_dispatch` in a workflow if that is helpful for testing, but I have some questions about how that would work. 

If you are on a branch called `my-feature` and then want to deploy the code, will you run a workflow manually (using `workflow_dispatch`), will that create an image with a tag called `my-feature`? I might be misunderstanding this part. I think this means you will need tag immutability set on the ECR repo, which is OK.

**Review by briancaffey — APPROVED** [review]

**Pull request merged**
